=== badvision/Apple-game-server/src/ags/resources/ags.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://badvision.org"
    xmlns:tns="http://badvision.org"
    elementFormDefault="qualified">
    <xsd:element name="games">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tns:game" maxOccurs="unbounded" minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="game">
        <xsd:annotation>
            <xsd:documentation>Describes a game as a single file to be executed, a series of parts (see part), or a collection of disks</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
<!--            <xsd:attribute name="start" type="xsd:hexBinary" use="optional"> -->
            <xsd:complexContent>
                <xsd:extension xmlns:tns="http://badvision.org" base="tns:gameBase">
                    <xsd:sequence>
                        <xsd:element name="author" minOccurs="0">
                            <xsd:annotation>
                                    <xsd:documentation>
                            Name of author and/or publisher
                        </xsd:documentation>
                                </xsd:annotation>
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string"/>
                                </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="description" maxOccurs="1" minOccurs="0">
                            <xsd:annotation>
                                    <xsd:documentation>Description of game</xsd:documentation>
                                </xsd:annotation>
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string"/>
                                </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="part" maxOccurs="unbounded" minOccurs="0" type="tns:part" xmlns:tns="http://badvision.org"></xsd:element>
                        <xsd:element name="screenshot" maxOccurs="unbounded" minOccurs="0">
                            <xsd:annotation>
                                    <xsd:documentation>One or more screenshot images for game.  File must be relative to the xml file's location</xsd:documentation>
                                </xsd:annotation>
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string"/>
                                </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="year" minOccurs="0">
                            <xsd:annotation>
                                    <xsd:documentation>Year that game was published</xsd:documentation>
                                </xsd:annotation>
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string"/>
                                </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="disk" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                                    <xsd:sequence/>
                                        <xsd:attribute name="name" type="xsd:string" use="required">
                                            <xsd:annotation>
                                                    <xsd:documentation>Name of disk image (e.g. player disk, save disk)</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:attribute>
                                        <xsd:attribute name="file" type="xsd:string" use="required">
                                            <xsd:annotation>
                                                    <xsd:documentation>file containing disk image</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:attribute>
                                        <xsd:attribute name="slot" type="xsd:int">
                                            <xsd:annotation>
                                                    <xsd:documentation>Preferred slot for disk</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:attribute>
                                        <xsd:attribute name="drive" type="xsd:int">
                                            <xsd:annotation>
                                                    <xsd:documentation>Preferred drive for disk</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:attribute>
                                        <xsd:attribute name="volume" type="xsd:int">
                                            <xsd:annotation>
                                                    <xsd:documentation>Preferred DOS 3.3 volume for disk</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:attribute>
                                </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                    <xsd:attribute name="supportsKeyboard" type="xsd:boolean">
                        <xsd:annotation>
                                <xsd:documentation>Supports keyboard?  If unspecified, then "unknown" is assumed</xsd:documentation>
                            </xsd:annotation>
                    </xsd:attribute>
                    <xsd:attribute name="supportsJoystick" type="xsd:boolean">
                        <xsd:annotation>
                                <xsd:documentation>Supports joystick?  If unspecified, then "unknown" is assumed</xsd:documentation>
                            </xsd:annotation>
                    </xsd:attribute>
                    <xsd:attribute name="supportsMouse" type="xsd:boolean">
                        <xsd:annotation>
                                <xsd:documentation>Supports mouse?  If unspecified, then "unknown" is assumed</xsd:documentation>
                            </xsd:annotation>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:complexContent>
        </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="hex">
        <xsd:annotation>
            <xsd:documentation>Any hexadecimal number that is between 1 and 4 digits long, case insensitive</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction>
            <xsd:simpleType>
                <xsd:restriction base="xsd:string"/>
            </xsd:simpleType>
            <xsd:pattern id="hex" value="[0-9a-fA-F]{1,4}"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="gameBase">
        <xsd:attribute name="file" type="xsd:string" use="optional">
            <xsd:annotation>
                    <xsd:documentation>File containing game (for single disk or single-part games)</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="required">
            <xsd:annotation>
                    <xsd:documentation>Name of game (must be less than 39 characters for display reasons)</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="start" type="tns:hex" use="optional">
            <xsd:annotation>
                    <xsd:documentation>For single-part, non disk-based games this specifies where game is loaded into memory.</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="type" type="xsd:string" use="required">
            <xsd:annotation>
                    <xsd:documentation>Overall game type
06: binary (can include multiple parts)
fc: basic (can include binary parts)
disk: disk-based game (can include multiple disks)</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="part">
        <xsd:complexContent>
            <xsd:extension xmlns:tns="http://badvision.org" base="tns:gameBase">
                <xsd:sequence/>
        <xsd:attribute name="length" type="tns:hex">
            <xsd:annotation>
                    <xsd:documentation>Length of data to send -- if not specified then rest of file will be sent</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="offset" type="tns:hex">
            <xsd:annotation>
                    <xsd:documentation>Offset of data file to start from, if not specified will assume start of file</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="action" type="xsd:string" use="required">
            <xsd:annotation>
                    <xsd:documentation>Action to perform.  Can be one of:
load (only load into memory)
subroutine (execute but expect RTS to return)
run (start program, terminate AGS)</xsd:documentation>
                </xsd:annotation>
        </xsd:attribute>

            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
</xsd:schema>

=== badvision/Apple-game-server/a2gameserver/lib/data/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : games.xml
    Created on : May 17, 2006, 6:34 PM
    Author     : brobert
    Description:
        Lists all games and other necessary information
-->
<games xmlns="http://badvision.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://badvision.org file://home/brobert/Documents/Personal/a2gameserver/src/resources/ags.xsd">
    <game file="AGENT.USA#060801" name="Agent USA" start="0801" type="06">
        <author>Tom Snyder / Scholastic</author>
        <description>This is an educational game designed to teach US State Capitals. It is focused around a mutant television set, called the "Fuzzbomb" which infects United States cities.
            Agent USA can defeat the Fuzzbomb by growing energy crystals, and travels the United States via train, encoutering "fuzzed cities" along the way.
            Beware the mutant inhabitants, which take the Agent's crystals.</description>
        <screenshot>agentusa1.png</screenshot>
        <screenshot>agentusa2.png</screenshot>
        <year>1984</year>
    </game>

    <game file="AIR.CARS#066000" name="Air Cars" start="6000" type="06">
        <author/>
        <description/>
        <screenshot>aircars1.png</screenshot>
        <year/>
    </game>

    <game file="ALCAZAR#0607fd" name="Alcazar" start="07fd" type="06">
        <author>Tom Loughry / Activision</author>
        <description>In this adventure game you control an explorer who's on his way to fortress
            Alcazar. To reach Alcazar you are travelling through a countryside of fortresses and you
            need to collect several items that you can find along the way. Once you enter the
            Alcazar fortress you have to search for the crown.</description>
        <screenshot/>
        <year>1985</year>
    </game>

    <game file="ALIEN.AMBUSH#064000" name="Alien Ambush" start="4000" supportsKeyboard="false" type="06">
        <author>Micro D / DANA</author>
        <description>A rather simple, yet original, vertical space shooter. You control a small
            space fighter tasked with extermination of hordes of alien spaceships. At first,
            different slow moving motherships attack you in four separate waves. When hit they
            release two smaller but much faster moving shuttles. To progress to the next attack wave
            the player must shoot down both the mothership and the two shuttles capsules while
            evading getting hit by either.</description>
        <screenshot/>
        <year>1983</year>
    </game>

    <game file="ALIEN.GAME#0607fd" name="Alien Game" start="07fd" type="06">
        <author/>
        <description/>
        <screenshot>aliengame1.png</screenshot>
        <year/>
    </game>

    <game file="ALIEN.MUNCHIES#064790" name="Alien Munchies" start="4790" type="06">
        <author/>
        <description/>
        <screenshot>alienmunchies1.png</screenshot>
        <screenshot>alienmunchies2.png</screenshot>
        <year/>
    </game>

    <game file="ALIEN.TYPHOON#060fe0" name="Alien Typhoon" start="0fe0" type="06">
        <author>Star Craft</author>
        <description>Alien Typhoon is a clone of the arcade game Galaxian. It is a shoot-'em-up
            where a formation of alien ships attack your lone starship at the bottom of the screen.
            The aliens peel off from the formation and attack you in different patterns, depending
            on the color of the ship. The two ships at the top are the motherships and they bring an
            escort of two red aliens with them to guard them, but if you can shoot the escort and
            then the mothership, you'll score lots of points.</description>
        <screenshot>alientyphoon1.png</screenshot>
        <screenshot>alientyphoon2.png</screenshot>
        <year>1981</year>
    </game>

    <game file="ALIVADER#060200" name="Alivader" start="0200" type="06">
        <author/>
        <description/>
        <screenshot>alivader.png</screenshot>
        <year/>
    </game>

    <game file="ALL.STAR.BASEBA#fc0801" name="All Star Baseball" start="0801" type="fc">
        <author/>
        <description>Really slow applesoft-based baseball game</description>
        <screenshot/>
        <year/>
    </game>

    <game file="APE.ESCAPE#0607fd" name="Ape Escape" start="07fd" type="06">
        <author/>
        <description/>
        <screenshot>apeescape1.png</screenshot>
        <year/>
    </game>

    <game file="APPLE.OIDS#061ffd" name="Apple Oids" start="1ffd" type="06">
        <author/>
        <description/>
        <screenshot>appleoids1.png</screenshot>
        <year/>
    </game>

    <game name="Apple Panic" supportsKeyboard="true" supportsJoystick="false" supportsMouse="false" type="06">
        <author>Olaf Lubeck / Broderbund</author>
        <description>You control a digger, armed with his shovel, and you must kill your opponents -
            the evil legged apples. Your character can only walk left/right and climb up/down the
            ladders - no jumping - and if the apples touch you, you'll lose. To kill an apple you
            must dig a hole on the ground and wait for one of them to get stuck on it. Then you must
            hit it with your shovel to make it fall.</description>
        <part action="subroutine" file="APL.PANIC.TITLE#0626fd" name="Apple Panic Title" start="26fd" type="06"/>
        <part action="run" file="APPLE.PANIC#064000" name="Apple Panic" start="4000" type="06"/>
        <screenshot>applepanic2.png</screenshot>
        <year>1981</year>
    </game>

    <game file="APPLE.PANIC.JOY#0607fd" name="Apple Panic Joystick" start="07fd" type="06">
        <author>Olaf Lubeck / Broderbund</author>
        <description>Joystick-only variant of Apple Panic</description>
        <screenshot>applepanic2.png</screenshot>
        <year>1981</year>
    </game>

    <game file="APPLE.ZAP#063ffd" name="Apple Zap" start="3ffd" type="06">
        <author/>
        <description/>
        <screenshot>applezap1.png</screenshot>
        <year/>
    </game>

    <game file="AQUATRON#060801" name="Aquatron" start="0801" type="06">
        <author>Sierra On-Line</author>
        <description>It's just you and your jet, which can also 'fly' underwater, against massive
            spawning armadas of aliens. Scrolls at lightspeed and makes you sweat heavily. Cheats:
            Level skip [Ctrl] + @, Restart [Ctrl] + C or R, Reselect controls: [Ctrl] + I, Turn
            around instantly: [Ctrl] + T</description>
        <screenshot>aquatron1.png</screenshot>
        <screenshot>aquatron2.png</screenshot>
        <year>1983</year>
    </game>

    <game file="ArcadeBootCamp.dsk" name="Arcade Boot Camp" supportsKeyboard="false" supportsJoystick="1" supportsMouse="0" type="disk">
        <screenshot/>
    </game>

    <game file="ARENA.OF.OCTOS#fc0801" name="Arena of Octos" start="0801" type="fc">
        <author/>
        <description/>
        <screenshot/>
        <year/>
    </game>

    <game file="ASTEROIDS#060800" name="Asteroids" start="0800" type="06">
        <author>Atari</author>
        <description>Asteroids is a conversion of the popular arcade game. You are the pilot of a
            spaceship trapped in the asteroid belt, and you need to blast your way out! Each time
            you shoot one of the asteroids, it will break up into smaller pieces. Eventually the
            pieces will become small enough that they can be destroyed. When all asteroids have been
            fully destroyed, you can move on to the next, more difficult round. Just in case the
            numerous asteroids didn't cause you enough trouble, a pesky flying saucer will appear
            from time to time and try to shoot your spaceship with torpedoes.</description>
        <screenshot>asteroids1.png</screenshot>
        <year>1981</year>
    </game>

    <game file="AUTOBAHN#060801" name="Autobahn" start="0801" supportsKeyboard="false" supportsJoystick="true" type="06">
        <author>Nasir Gebelli / Sirius Software</author>
        <description>A clone of the arcade game Monaco GP, Autobahn is a very simple and fast arcade
            racer. As you blaze down the roadway you must avoid colliding with other cars and road
            hazards. You have three speeds you can run your car at and the high score is determined
            by the number of miles you've driven. Ctrl-P switches to Paddles.</description>
        <screenshot>autobahn1.png</screenshot>
        <screenshot>autobahn2.png</screenshot>
        <year>1981</year>
    </game>

    <game file="B1.BOMBER#fc0801" name="B1 Bomber" start="0801" type="fc">
        <author/>
        <description/>
        <screenshot/>
        <year/>
    </game>

    <game file="BALLBLAZER#0607fd" name="BallBlazer" start="07fd" type="06">
        <author>Lucasfilm Games / Epyx</author>
        <description>Ballblazer is a one-on-one soccer match set in the future. You control a robot
            and try to snare a floating ball called a Plasmorb, which could then be fired or carried
            into the opponent's goal. You play on a simple 3d playfield which is split in half. You
            can play against the computer or against another robot controlled by a human
            player.</description>
        <screenshot>ballblazer1.png</screenshot>
        <screenshot>ballblazer2.png</screenshot>
        <year>1985</year>
    </game>

    <game file="BATTLE.AT.SEA#fc0801" name="Battle At Sea" start="0801" type="fc">
        <author/>
        <description/>
        <screenshot/>
        <year/>
    </game>

    <game file="BATTLE.CRUISER#060803" name="!Battle Cruiser" start="0803" type="06">
        <author/>
        <description/>
        <screenshot/>
        <year/>
    </game>

    <game file="BCQUEST#0607fd" name="BC's Quest for Tires" start="07fd" type="06">
        <author>Sydney Development Group / Sierra On-Line </author>
